name: CI_CodeQualityEnforcer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-quality-enforcer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      #- name: Pytype Python Checker Enforcer
      # uses: theahura/pytype-action@v1.2

      - name: Dockerfile Validator Enforcer
        uses: ghe-actions/dockerfile-validator@v1

      - name: Xenon Enforcer
        run: |
          python${{ matrix.python-version }} -m pip install xenon
          xenon --ignore=venv --max-absolute=B --max-average=A .

      - name: Python Blacken Enforcer
        uses: piotrpawlaczek/python-blacken@v20.8b1
        with:
          line-length: 79

      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.3.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-black: false
          use-flake8: true
          use-mypy: true
          use-isort: true
          # Extra options: mypy $(extra-mypy-options) $(python-root-list)
          # extra-mypy-options: # optional, default is

      - name: docstr-coverage Enforcer
        uses: skazazes-work/docstr-coverage-action@v1.4
